Prepareed by : **Ashpak Sheikh**

Problem statement:
<br>Here is the time series data [110,125,133,146,158,172,187,196,210]. 
Build RNN/LSTM model to predict the next 10 digits.


In [1]:
#importing required libraries
import pandas as pd
import numpy as np
from numpy import array
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional

In [2]:
# univariate data preparation
from numpy import array
 
# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
    X, y = list(), list()
    for i in range(len(sequence)):
    # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the sequence
        if end_ix > len(sequence)-1:
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)

In [3]:
raw_seq = [110,125,133,146,158,172,187,196,210]


In [4]:
# choose a number of time steps
n_steps = 3
# split into samples
X, y = split_sequence(raw_seq, n_steps)

In [5]:
# summarize the data
for i in range(len(X)):
    print(X[i], y[i])

[110 125 133] 146
[125 133 146] 158
[133 146 158] 172
[146 158 172] 187
[158 172 187] 196
[172 187 196] 210


In [6]:
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))

In [7]:
X

array([[[110],
        [125],
        [133]],

       [[125],
        [133],
        [146]],

       [[133],
        [146],
        [158]],

       [[146],
        [158],
        [172]],

       [[158],
        [172],
        [187]],

       [[172],
        [187],
        [196]]])

In [8]:
n_feature = 1

In [9]:
model = Sequential()
model.add(Bidirectional(LSTM(50, activation='relu'),input_shape = (n_steps,n_feature)))
model.add(Dense(1))
model.compile(optimizer='adam',loss='mse')


In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
bidirectional (Bidirectional (None, 100)               20800     
_________________________________________________________________
dense (Dense)                (None, 1)                 101       
Total params: 20,901
Trainable params: 20,901
Non-trainable params: 0
_________________________________________________________________


In [11]:
# fit model
model.fit(X, y, epochs=200, verbose=0)

In [12]:
#prediction
x_input = array([110,125,133])
x_input = x_input.reshape((1,n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[147.0937]]


In [13]:
#printing next 10 values
for i in range(10):
    x_input = np.array(raw_seq[-3:])
    x_input = x_input.reshape((1,n_steps, n_features))
    yhat = model.predict(x_input, verbose=0)
    w=int(yhat)
    raw_seq.append(w)
    print(w)

224
237
252
267
283
300
318
336
356
377
